# 闭包的经典误区

- 函数定义时，不执行
  
- 注意变量做用域，**<font color="red"> 在闭包时，如果变量名字相同，内部函数应引入闭包后的外部变量；如果，在内部函数中重新赋值，则闭包不成立</font>**
```python  
def f1():
    a = 10
    def f2():
         c = 20 * a
         return c
    return f2

f = f1()
print(f)
print(f.__closure__)

<function f1.<locals>.f2 at 0x00C39CD8>
(<cell at 0x00BFDD30: int object at 0x6E676540>,)
```
```python
# 闭包不成立，a 在内部函数被重新赋值

def f1():
    a = 10
    def f2():
        a = 20  #   a 此时将被 python认位是一个局部变量
        print(a)
        return a
    return f2


f = f1()
print(f)
print(f.__closure__)

# <function f1.<locals>.f2 at 0x01429CD8>
# None
```

```python
# 闭包不成立，a 在内部函数被重新赋值
def f1():
    a = 10
    def f2():
        a = 20  #   a 此时将被 python认位是一个局部变量
        print(a)
    print(a)
    f2()
    print(a)

f1()

# 10
# 20
# 10
```